In [8]:
import time as t
import numpy as np
x = np.random. random(1000000) # genera un arreglo aleatorio de datos enteros
start = t.time()           # toma el tiempo inicial
sum(x)/len(x)               # promedio
end = t.time() - start     # calcula cuando demora el ciclo
print('function elapsed ',end)

function elapsed  0.1779165267944336


In [10]:
import time as t
import numpy as np
x = np.random. random(1000000) # genera un arreglo aleatorio de datos enteros
start = t.time()           # toma el tiempo inicial
np.sum(x)/len(x)               # promedio
end = t.time() - start     # calcula cuando demora el ciclo
print('function elapsed ',end)

function elapsed  0.0019996166229248047


In [11]:
import numpy as np
x = np.zeros((5,8))
x

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
import numpy as np
x = np.ones((3,4))
y = np.eye(5)
print(x)
print()
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
import numpy as np
x = np.linspace(0, 30, 20, endpoint=False)
x = np.reshape(x, (5,4))
print(x)

[[ 0.   1.5  3.   4.5]
 [ 6.   7.5  9.  10.5]
 [12.  13.5 15.  16.5]
 [18.  19.5 21.  22.5]
 [24.  25.5 27.  28.5]]


In [14]:
import numpy as np
x = np.full((4,4),2.2)
print(x)

[[2.2 2.2 2.2 2.2]
 [2.2 2.2 2.2 2.2]
 [2.2 2.2 2.2 2.2]
 [2.2 2.2 2.2 2.2]]


In [18]:
import numpy as np
x = np.array(np.arange(20).reshape(10,2))
x[9,1] = -2
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 -2]]


In [1]:
import numpy as np
x = np.arange(2,14,2).reshape((2,3))
print(x)
print()
x = np.arange(14,26,2).reshape((2,3))
print(x)
print()
x = np.arange(26,38,2).reshape((2,3))
print(x)
print()
x = np.arange(38,50,2).reshape((2,3))
print(x)
print()
x = np.arange(50,62,2).reshape((2,3))
print(x)

[[ 2  4  6]
 [ 8 10 12]]

[[14 16 18]
 [20 22 24]]

[[26 28 30]
 [32 34 36]]

[[38 40 42]
 [44 46 48]]

[[50 52 54]
 [56 58 60]]


In [2]:
import numpy as np
x = np.arange(1,31).reshape((5,6))
print(x)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [5]:
import numpy as np
primos = (x[x%2==1])
print(primos)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [7]:
a = np.zeros((4,8))
print(a)
b = np.array([1,2,3,4,5,6,7,8])
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[1 2 3 4 5 6 7 8]


In [8]:
import numpy as np
a[:, 0] =  1
a[:, 1] =  2
a[:, 2] =  3
a[:, 3] =  4
a[:, 4] =  5
a[:, 5] =  6
a[:, 6] =  7
a[:, 7] =  8
print(a)

[[1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]]
